<a href="https://www.kaggle.com/code/mumerfarooqbajwa/gradient-descent?scriptVersionId=341864597" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/camnugent/california-housing-prices/housing.csv
/kaggle/input/datasets/mirichoi0218/insurance/insurance.csv
/kaggle/input/datasets/mdabdulla072/linear-regression-lv0/data.csv

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("camnugent/california-housing-prices")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/camnugent/california-housing-prices

In [3]:
import pandas as pd
import numpy as np

from sklearn import set_config

set_config(transform_output='pandas')

In [4]:
df = pd.read_csv("/kaggle/input/datasets/camnugent/california-housing-prices/housing.csv")

In [5]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [6]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mirichoi0218/insurance")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/mirichoi0218/insurance

In [7]:
df = pd.read_csv("/kaggle/input/datasets/mirichoi0218/insurance/insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(df.iloc[:, :-1], df.iloc[:, -1], test_size= 0.2, random_state =42)

X_train, X_test, y_train, y_test

(      age     sex     bmi  children smoker     region
 560    46  female  19.950         2     no  northwest
 1285   47  female  24.320         0     no  northeast
 1142   52  female  24.860         0     no  southeast
 969    39  female  34.320         5     no  southeast
 486    54  female  21.470         3     no  northwest
 ...   ...     ...     ...       ...    ...        ...
 1095   18  female  31.350         4     no  northeast
 1130   39  female  23.870         5     no  southeast
 1294   58    male  25.175         0     no  northeast
 860    37  female  47.600         2    yes  southwest
 1126   55    male  29.900         0     no  southwest

 [1070 rows x 6 columns],
       age     sex     bmi  children smoker     region
 764    45  female  25.175         2     no  northeast
 887    36  female  30.020         0     no  northwest
 890    64  female  26.885         0    yes  northwest
 1293   46    male  25.745         3     no  northwest
 259    19    male  31.920         0    yes  northwest
 ...   ...     ...     ...       ...    ...        ...
 109    63    male  35.090         0    yes  southeast
 575    58  female  27.170         0     no  northwest
 535    38    male  28.025         1     no  northeast
 543    54  female  47.410         0    yes  southeast
 846    51  female  34.200         1     no  southwest

 [268 rows x 6 columns],
 560      9193.83850
 1285     8534.67180
 1142    27117.99378
 969      8596.82780
 486     12475.35130
            ...
 1095     4561.18850
 1130     8582.30230
 1294    11931.12525
 860     46113.51100
 1126    10214.63600
 Name: charges, Length: 1070, dtype: float64,
 764      9095.06825
 887      5272.17580
 890     29330.98315
 1293     9301.89355
 259     33750.29180
            ...
 109     47055.53210
 575     12222.89830
 535      6067.12675
 543     63770.42801
 846      9872.70100
 Name: charges, Length: 268, dtype: float64)

In [10]:
print(type(X_train))
print(type(X_test))
print(type(y_train))
print(type(y_test))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [11]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

from sklearn.preprocessing import StandardScaler


from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline


rtf= ColumnTransformer([('ohe', OneHotEncoder(drop='first', handle_unknown='error', sparse_output= False ), ['sex', 'region']),
                       ('oe', OrdinalEncoder(categories=[['no','yes']]), ['smoker'] ),],
                      remainder='passthrough')

pipeline = Pipeline ([
    ('encoding', rtf)
    #('scaler', StandardScaler())
])

In [12]:
pipeline.fit(X_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['sex', 'region']),
                                                 ('oe',
                                                  OrdinalEncoder(categories=[['no',
                                                                              'yes']]),
                                                  ['smoker'])]))])

In [13]:
X_train_trf = pipeline.transform(X_train)
X_test_trf = pipeline.transform (X_test)

In [14]:
display(X_train_trf)

,ohe__sex_male,ohe__region_northwest,ohe__region_southeast,ohe__region_southwest,oe__smoker,remainder__age,remainder__bmi,remainder__children
560,0.0,1.0,0.0,0.0,0.0,46,19.950,2
1285,0.0,0.0,0.0,0.0,0.0,47,24.320,0
1142,0.0,0.0,1.0,0.0,0.0,52,24.860,0
969,0.0,0.0,1.0,0.0,0.0,39,34.320,5
486,0.0,1.0,0.0,0.0,0.0,54,21.470,3
...,...,...,...,...,...,...,...,...
1095,0.0,0.0,0.0,0.0,0.0,18,31.350,4
1130,0.0,0.0,1.0,0.0,0.0,39,23.870,5
1294,1.0,0.0,0.0,0.0,0.0,58,25.175,0
860,0.0,0.0,0.0,1.0,1.0,37,47.600,2
1126,1.0,0.0,0.0,1.0,0.0,55,29.900,0

# **Gradient Descent Implementaion**

In [15]:
class GDRegressor:

    def __init__ (self, learning_rate=0.001, epochs=100):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train, y_train):
        #changing pandas dataframe into arrays
        X_train = X_train.values if hasattr(X_train, 'values') else np.asarray(X_train)
        y_train = y_train.values if hasattr(y_train, 'values') else np.asarray(y_train)
        
        self.intercept_ = 0
        self.coef_ = np.array([1 for i in range (X_train.shape[1])])

        # intercept (beta-not) = intercept - learning_rate (eeta) * slope of loss function ( like mse)
        
        # slope can be calculated by derivative
        
        # y_hat is predicted y (with previous weights)
        for k in range(self.epochs):
            y_hat = np.dot( X_train, self.coef_.reshape(self.coef_.shape[0],1) ) + self.intercept_   # self.coef_ 1D, X_train 2D, so y-hat is 1D ie predicted y for whole X_train instead of one row only
            
            y_hat = y_hat.reshape(-1)
            
            error_difference = y_train - y_hat
            
            der_intercept = -2* np.mean(error_difference)
            
            # updating intercept
            self.intercept_ = self.intercept_ - self.learning_rate * der_intercept
            
            # der_Beta_one ie. slope with respect to X1 of any row 
            #  der_beta_one = 2 / n  * sum ( (y - y_hat) * X1)
            #  generally for each beta/weight:
            # der_coef_[i] = 2 * np.mean((y_train- y_hat)*X_train[i])

            der_coef_ = np.dot(error_difference , X_train) # yet to calucalte its 2 * mean 
            der_coef_ = -2/X_train.shape[0] * der_coef_
            
            #updating coef_ weights
            self.coef_ = self.coef_ - self.learning_rate * der_coef_

    def predict(self,X_test):
        X_test = X_test.values if hasattr(X_test, 'values') else np.asarray(X_test)
        return np.dot(X_test, self.coef_) + self.intercept

In [16]:
reg = GDRegressor()

reg.fit(X_train_trf, y_train)

In [17]:
import numpy as np
import pandas as pd

from sklearn.linear_model import SGDRegressor
x1= np.array([1,2,3,4,5,6,7,8,9,10])
x2= np.array([2,54,2,6,78,8,3,5,6,7])
y = []

for i in range(x1.shape[0]):
    y.append(x1[i]*3 + x2[i])

df= pd.DataFrame({'x1':x1 , 
                             'x2': x2,
                             'y': y})
reg = SGDRegressor(max_iter=100)

reg.fit(df.iloc[:,:-1], df.iloc[:, -1])

X_test = pd.DataFrame({'x1':np.array([i+10 for i in range(10) ]),
                       'x2':np.array([i+3  for i in range(10)])})
print(reg.coef_)
print(reg.intercept_)

[ 6.55083467e+10 -2.12427330e+11]
[7.80414845e+09]

In [18]:
from sklearn.linear_model import LinearRegression


x1= np.array([1,2,3,4,5,6,7,8,9,10])
x2= np.array([2,54,2,6,78,8,3,5,6,7])
y = []

for i in range(x1.shape[0]):
    y.append(x1[i]*3 + x2[i])

df= pd.DataFrame({'x1':x1 , 
                             'x2': x2,
                             'y': y})
reg = LinearRegression()

reg.fit(df.iloc[:,:-1], df.iloc[:, -1])

X_test = pd.DataFrame({'x1':np.array([i+10 for i in range(10) ]),
                       'x2':np.array([i+3  for i in range(10)])})

print("intercept:", reg.intercept_)
print("coef_ ", reg.coef_)
predicted_y = reg.predict(df.iloc[:,:-1])

intercept: -7.105427357601002e-15
coef_  [3. 1.]

In [19]:
"""y_train = df.iloc[:, -1]
y =  y_train.values if hasattr(y_train, 'values') else np.asarray(y_train)
y2 = np.array(y_train)
"""
from sklearn.metrics import r2_score
r2_score(predicted_y, df.iloc[:, -1])
#np.array(y_train)
#predicted_y

1.0