In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/organizations/uciml/adult-census-income/adult.csv

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/adult-census-income")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/organizations/uciml/adult-census-income

In [3]:
import pandas as pd
df = pd.read_csv("/kaggle/input/datasets/organizations/uciml/adult-census-income/adult.csv")

In [4]:
df = df.drop(columns=["education.num","relationship"])
df.sample(5)

,age,workclass,fnlwgt,education,marital.status,occupation,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
3974,53,Private,233780,Assoc-voc,Divorced,Adm-clerical,Black,Female,2202,0,40,United-States,<=50K
751,38,Private,278924,Bachelors,Married-civ-spouse,Exec-managerial,White,Male,0,1887,50,United-States,>50K
6381,19,?,356717,Some-college,Never-married,?,White,Female,0,0,25,United-States,<=50K
16446,50,Self-emp-inc,104849,Prof-school,Married-civ-spouse,Prof-specialty,Asian-Pac-Islander,Male,0,0,40,India,<=50K
17381,44,Self-emp-inc,456236,Some-college,Divorced,Sales,White,Male,0,0,45,United-States,>50K

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test, Y_train, Y_test = train_test_split(df.drop(columns=['income']), df['income'], test_size=0.2, random_state=42)
X_train

,age,workclass,fnlwgt,education,marital.status,occupation,race,sex,capital.gain,capital.loss,hours.per.week,native.country
5514,26,Private,256263,HS-grad,Never-married,Craft-repair,White,Male,0,0,25,United-States
19777,24,Private,170277,HS-grad,Never-married,Other-service,White,Female,0,0,35,United-States
10781,36,Private,75826,Bachelors,Divorced,Adm-clerical,White,Female,0,0,40,United-States
32240,22,State-gov,24395,Some-college,Married-civ-spouse,Adm-clerical,White,Female,0,0,20,United-States
9876,31,Local-gov,356689,Bachelors,Married-civ-spouse,Prof-specialty,White,Male,0,0,40,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...
29802,25,Private,410240,HS-grad,Never-married,Craft-repair,White,Male,0,0,40,United-States
5390,51,Private,146767,Assoc-voc,Married-civ-spouse,Prof-specialty,White,Male,0,0,40,United-States
860,55,Federal-gov,238192,HS-grad,Married-civ-spouse,Tech-support,White,Male,0,1887,40,United-States
15795,41,Private,154076,Some-college,Married-civ-spouse,Adm-clerical,White,Male,0,0,50,United-States
23654,22,Private,162667,HS-grad,Never-married,Handlers-cleaners,White,Male,0,0,50,Portugal

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder
from sklearn.pipeline import Pipeline , make_pipeline

In [8]:
trf1 = ColumnTransformer([(
        "education_oe",OrdinalEncoder (categories=[["Preschool","1st-4th",'5th-6th','7th-8th','9th','10th','HS-grad','11th','12th','Some-college','Prof-school','Assoc-acdm','Assoc-voc','Bachelors','Masters','Doctorate']], handle_unknown='error'),[3]
    )],
remainder= 'passthrough')
#array(['HS-grad', 'Bachelors', 'Some-college', '11th', '5th-6th',
#       'Assoc-voc', 'Masters', '9th', 'Doctorate', 'Prof-school',
#       '7th-8th', '10th', '12th', '1st-4th', 'Assoc-acdm', 'Preschool'],
#      dtype=object)

In [9]:
trf2 = ColumnTransformer ([(
'ohe' , OneHotEncoder(drop='first',sparse_output=False, handle_unknown = 'ignore'), [2,4,5,6,7,11]
)], 
remainder= 'passthrough')

In [10]:
from sklearn.tree import DecisionTreeClassifier

trf3 = DecisionTreeClassifier()

In [11]:
pipeline = Pipeline([
    ('trf1', trf1),
    ('trf2', trf2),
    ('trf3', trf3)
])

In [12]:
X_train['education'].unique()

array(['HS-grad', 'Bachelors', 'Some-college', '11th', '5th-6th',
       'Assoc-voc', 'Masters', '9th', 'Doctorate', 'Prof-school',
       '7th-8th', '10th', '12th', '1st-4th', 'Assoc-acdm', 'Preschool'],
      dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [14]:
pipeline.fit(X_train, Y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('education_oe',
                                                  OrdinalEncoder(categories=[['Preschool',
                                                                              '1st-4th',
                                                                              '5th-6th',
                                                                              '7th-8th',
                                                                              '9th',
                                                                              '10th',
                                                                              'HS-grad',
                                                                              '11th',
                                                                              '12th',
                                                                              'Some-college',
                                                                              'Prof-school',
                                                                              'Assoc-acdm',
                                                                              'Assoc-voc',
                                                                              'Bachelors',
                                                                              'Masters',
                                                                              'Doctorate']]),
                                                  [3])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [2, 4, 5, 6, 7, 11])])),
                ('trf3', DecisionTreeClassifier())])

In [15]:
predicted_Y= pipeline.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, predicted_Y)

0.8128358667280823

# Exporting the Pipeline with Pickle

In [17]:
import pickle

In [18]:
pickle.dump(pipeline, open('income_pipeline.pkl','wb'))
#wb maybe stands for 'write binary'

# Using Pipleline.pkl on Production Side

In [19]:
import pickle
import numpy as np

In [20]:
pipe = pickle.load(open('income_pipeline.pkl', 'rb'))
#'rb' most probably stands for 'read binary'

In [21]:
#input_array = np.array([])
df.sample(5)

,age,workclass,fnlwgt,education,marital.status,occupation,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
30994,49,Self-emp-inc,122066,Some-college,Divorced,Sales,White,Male,0,0,25,United-States,<=50K
25286,77,Private,154205,HS-grad,Widowed,Adm-clerical,White,Female,0,0,10,United-States,<=50K
3868,26,Private,262617,HS-grad,Never-married,Craft-repair,White,Male,2597,0,40,United-States,<=50K
8636,34,Private,178615,HS-grad,Married-civ-spouse,Machine-op-inspct,White,Male,0,0,40,United-States,<=50K
21223,38,State-gov,142022,HS-grad,Married-civ-spouse,Adm-clerical,Black,Female,0,0,40,United-States,<=50K

In [22]:
input_array = np.array([59,'Self-emp-inc',107287,'10th','Widowed','Exec-manageria','White','Female',0,2559,50,'United-States'], dtype=object).reshape(1,12)

In [23]:
pipe.predict(input_array)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

array(['>50K'], dtype=object)